### ISSUE TITLE
Why do the package names and source code headers include name of a private company?

### ISSUE THREAD

**Issue by dagvadorj** [jbaliuka/x4j-analytic#15]
Is it really an open source project?

**Comment by jbaliuka** [comment]
Historicaly copyright belongs to EIS Group becasue this company invested here  but  code is open source and free

**Comment by dagvadorj** [comment]
Has that company gave away its copy right? If so, why don't you remove copy right headers from source codes? ;)

**Comment by jbaliuka** [comment]
It deserves a credit but I will remove  a copyright notice if someone from this company will ask for it, I do not own copyright, I just maintain this code historically .
